=== SoucianceEqdamRashti/Integration/CamelDemo/src/main/resources/jsonvalidate/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "_id": {
        "type": "string"
      },
      "index": {
        "type": "integer"
      },
      "guid": {
        "type": "string"
      },
      "isActive": {
        "type": "boolean"
      },
      "balance": {
        "type": "string"
      },
      "picture": {
        "type": "string"
      },
      "age": {
        "type": "integer"
      },
      "eyeColor": {
        "type": "string"
      },
      "name": {
        "type": "object",
        "properties": {
          "first": {
            "type": "string"
          },
          "last": {
            "type": "string"
          }
        },
        "required": [
          "first",
          "last"
        ]
      },
      "company": {
        "type": "string"
      },
      "email": {
        "type": "string"
      },
      "phone": {
        "type": "string"
      },
      "address": {
        "type": "string"
      },
      "about": {
        "type": "string"
      },
      "registered": {
        "type": "string"
      },
      "latitude": {
        "type": "string"
      },
      "longitude": {
        "type": "string"
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "range": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "friends": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        }
      },
      "greeting": {
        "type": "string"
      },
      "favoriteFruit": {
        "type": "string"
      }
    },
    "required": [
      "_id",
      "index",
      "guid",
      "isActive",
      "balance",
      "picture",
      "age",
      "eyeColor",
      "name",
      "company",
      "email",
      "phone",
      "address",
      "about",
      "registered",
      "latitude",
      "longitude",
      "tags",
      "range",
      "friends",
      "greeting",
      "favoriteFruit"
    ]
  }
}

=== SoucianceEqdamRashti/Integration/CamelDemo/src/main/resources/jsonvalidate/data.json
[
  {
    "_id": "587bcba3496b0749df9baa33",
    "index": 0,
    "guid": "37fe6a10-c0fc-4a5b-81ef-c98524d47866",
    "isActive": true,
    "balance": "$1,973.12",
    "picture": "http://placehold.it/32x32",
    "age": 28,
    "eyeColor": "green",
    "name": {
      "first": "Francis",
      "last": "Villarreal"
    },
    "company": "KOOGLE",
    "email": "francis.villarreal@koogle.biz",
    "phone": "+1 (932) 557-3004",
    "address": "215 Putnam Avenue, Blende, American Samoa, 2572",
    "about": "Do enim dolor ad sint consectetur aliqua ad aute dolore sunt. Esse irure labore laboris proident pariatur. Cillum ut irure elit ex deserunt voluptate officia cillum ex. Id irure aliqua minim cillum. Sint consectetur enim minim ut ullamco excepteur exercitation adipisicing ullamco amet.",
    "registered": "Thursday, April 2, 2015 9:19 PM",
    "latitude": "39.467148",
    "longitude": "-167.538699",
    "tags": [
      "labore",
      "do",
      "culpa",
      "nulla",
      "anim"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Ingrid Ewing"
      },
      {
        "id": 1,
        "name": "Concepcion Mcconnell"
      },
      {
        "id": 2,
        "name": "Jeanine Newman"
      }
    ],
    "greeting": "Hello, Francis! You have 9 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "587bcba3e15d32663fe0470b",
    "index": 1,
    "guid": "8d540c0f-d3a2-4ff6-9487-f9b9f0cf1737",
    "isActive": false,
    "balance": "$3,873.12",
    "picture": "http://placehold.it/32x32",
    "age": 23,
    "eyeColor": "green",
    "name": {
      "first": "Lindsey",
      "last": "Elliott"
    },
    "company": "RADIANTIX",
    "email": "lindsey.elliott@radiantix.biz",
    "phone": "+1 (969) 515-2901",
    "address": "595 Claver Place, Homeworth, Maryland, 3090",
    "about": "Esse consectetur labore esse incididunt do. Enim tempor voluptate enim consequat. Ipsum velit veniam sit consequat. Labore officia esse occaecat adipisicing minim ex mollit cupidatat.",
    "registered": "Monday, January 9, 2017 12:15 PM",
    "latitude": "-29.736423",
    "longitude": "162.50378",
    "tags": [
      "officia",
      "nisi",
      "duis",
      "in",
      "voluptate"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Kathrine Wilkins"
      },
      {
        "id": 1,
        "name": "Clemons Preston"
      },
      {
        "id": 2,
        "name": "Brooke Vaughn"
      }
    ],
    "greeting": "Hello, Lindsey! You have 10 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "587bcba445194d3c9976b76f",
    "index": 2,
    "guid": "d77b1379-99b6-419e-bea6-cc6f0b524710",
    "isActive": false,
    "balance": "$1,427.48",
    "picture": "http://placehold.it/32x32",
    "age": 34,
    "eyeColor": "brown",
    "name": {
      "first": "Tabitha",
      "last": "Morrison"
    },
    "company": "ZBOO",
    "email": "tabitha.morrison@zboo.me",
    "phone": "+1 (919) 406-2025",
    "address": "800 Estate Road, Savannah, Michigan, 6192",
    "about": "Enim proident elit pariatur minim quis. Eu fugiat proident ex exercitation. Laboris nisi labore fugiat mollit culpa. Duis labore nisi voluptate anim laboris ullamco excepteur proident duis et et. Proident commodo voluptate occaecat laborum tempor dolor enim non Lorem et anim elit. Eiusmod et id ut sit nisi tempor.",
    "registered": "Monday, September 21, 2015 12:34 PM",
    "latitude": "18.204709",
    "longitude": "72.813091",
    "tags": [
      "fugiat",
      "excepteur",
      "sunt",
      "culpa",
      "nisi"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Marsh Jenkins"
      },
      {
        "id": 1,
        "name": "Fry Hoover"
      },
      {
        "id": 2,
        "name": "Marcy Clemons"
      }
    ],
    "greeting": "Hello, Tabitha! You have 8 unread messages.",
    "favoriteFruit": "apple"
  },
  {
    "_id": "587bcba4c22f897495cc75f3",
    "index": 3,
    "guid": "fa30594b-faad-4d70-8f66-97b953d95d2c",
    "isActive": false,
    "balance": "$2,601.72",
    "picture": "http://placehold.it/32x32",
    "age": 22,
    "eyeColor": "brown",
    "name": {
      "first": "Mills",
      "last": "Burks"
    },
    "company": "SONGLINES",
    "email": "mills.burks@songlines.ca",
    "phone": "+1 (975) 565-2220",
    "address": "196 Anna Court, Summertown, California, 9139",
    "about": "Id elit laboris ut deserunt nulla duis mollit adipisicing pariatur commodo do. Tempor consectetur adipisicing labore nisi proident ut sint minim labore ut. Reprehenderit anim nostrud do incididunt aliqua. Esse fugiat tempor sunt sunt laboris.",
    "registered": "Thursday, December 11, 2014 8:09 AM",
    "latitude": "-5.449795",
    "longitude": "-136.411693",
    "tags": [
      "laborum",
      "laborum",
      "eiusmod",
      "labore",
      "anim"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Stein Oneal"
      },
      {
        "id": 1,
        "name": "Sexton Porter"
      },
      {
        "id": 2,
        "name": "French Tucker"
      }
    ],
    "greeting": "Hello, Mills! You have 9 unread messages.",
    "favoriteFruit": "strawberry"
  },
  {
    "_id": "587bcba4fcacc550cf63ad93",
    "index": 4,
    "guid": "4047d8e7-fc52-4891-b054-f68c9429dd0c",
    "isActive": true,
    "balance": "$1,719.78",
    "picture": "http://placehold.it/32x32",
    "age": 24,
    "eyeColor": "brown",
    "name": {
      "first": "Justice",
      "last": "Gross"
    },
    "company": "EXTRAWEAR",
    "email": "justice.gross@extrawear.info",
    "phone": "+1 (931) 559-2199",
    "address": "592 Blake Court, Abrams, Palau, 6546",
    "about": "Ex nisi dolor in aliqua exercitation non sunt proident nulla Lorem eiusmod aliqua consequat magna. Qui cupidatat officia duis voluptate id nulla enim sunt mollit nulla dolore fugiat. Aliquip et deserunt Lorem in aliqua amet consectetur. Adipisicing minim excepteur consequat eiusmod qui velit consequat incididunt fugiat. Minim reprehenderit sit sint ipsum Lorem laboris labore. Aliqua sunt non id quis aliquip consequat ea enim aliquip velit reprehenderit deserunt voluptate. In est sint eu deserunt laboris aliqua duis magna magna fugiat quis.",
    "registered": "Wednesday, November 16, 2016 11:21 AM",
    "latitude": "21.468006",
    "longitude": "-161.673839",
    "tags": [
      "elit",
      "labore",
      "Lorem",
      "minim",
      "labore"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Rogers Montoya"
      },
      {
        "id": 1,
        "name": "Lowe Weaver"
      },
      {
        "id": 2,
        "name": "Malone Cooke"
      }
    ],
    "greeting": "Hello, Justice! You have 5 unread messages.",
    "favoriteFruit": "banana"
  },
  {
    "_id": "587bcba4ca6ddf2de00bb0a6",
    "index": 5,
    "guid": "88e79723-5429-4cfa-af4d-e17125e1a803",
    "isActive": true,
    "balance": "$1,909.92",
    "picture": "http://placehold.it/32x32",
    "age": 27,
    "eyeColor": "green",
    "name": {
      "first": "Weeks",
      "last": "Sampson"
    },
    "company": "GEEKOL",
    "email": "weeks.sampson@geekol.co.uk",
    "phone": "+1 (996) 590-2144",
    "address": "234 Crown Street, Talpa, New Mexico, 7563",
    "about": "Irure dolor incididunt ut amet deserunt aliqua ex. Ex minim laborum minim aliquip quis eiusmod eiusmod et. Laboris tempor irure commodo commodo laboris anim.",
    "registered": "Friday, February 27, 2015 6:45 AM",
    "latitude": "25.978249",
    "longitude": "79.916109",
    "tags": [
      "ad",
      "ipsum",
      "reprehenderit",
      "ut",
      "officia"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Fuentes Mercer"
      },
      {
        "id": 1,
        "name": "Mcbride Fitzpatrick"
      },
      {
        "id": 2,
        "name": "Sondra Mcpherson"
      }
    ],
    "greeting": "Hello, Weeks! You have 8 unread messages.",
    "favoriteFruit": "banana"
  },
  {
    "_id": "587bcba46a14803311c0ebaf",
    "index": 6,
    "guid": "ee9a3843-266d-41e5-b9db-fd864748980b",
    "isActive": false,
    "balance": "$1,612.21",
    "picture": "http://placehold.it/32x32",
    "age": 37,
    "eyeColor": "green",
    "name": {
      "first": "Finch",
      "last": "Gentry"
    },
    "company": "MEDMEX",
    "email": "finch.gentry@medmex.org",
    "phone": "+1 (937) 590-3903",
    "address": "921 Holt Court, Singer, Mississippi, 1041",
    "about": "Nisi aliquip nulla do id eiusmod labore minim ipsum. Dolor deserunt ea ea laboris ipsum cillum minim exercitation duis. Dolore id eu reprehenderit Lorem nostrud magna minim deserunt mollit magna. Eiusmod do irure nostrud ad. Do voluptate Lorem laborum fugiat excepteur dolore. Officia minim est eiusmod laboris dolor sit do exercitation est. Eiusmod et cillum ipsum aliquip duis eiusmod aliquip laboris tempor tempor qui.",
    "registered": "Monday, April 14, 2014 8:22 PM",
    "latitude": "-35.30902",
    "longitude": "167.985492",
    "tags": [
      "adipisicing",
      "do",
      "exercitation",
      "proident",
      "et"
    ],
    "range": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "friends": [
      {
        "id": 0,
        "name": "Mavis Cannon"
      },
      {
        "id": 1,
        "name": "Rosa Burch"
      },
      {
        "id": 2,
